server:
  port: 9129

spring:
  application:
    name: hefconfig-server
  profiles:
    active: pro
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl